[package]
name = "ls"
version = "0.1.0"
authors = ["aiden01 <liangu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_grid = "0.1.7"
structopt = "0.2.18"
